spring:
  servlet:
    multipart:
      max-file-size: 4000KB
      max-request-size: 4000KB
  http:
    multipart:
      enabled: true
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
